### ISSUE TITLE
Specified no 360 but still 360'd 

### ISSUE THREAD

**Issue by Publicspac3** [rlcustomdesigns/form#8]
Created by: Spinonimus ♆#1257 (886315567194210354)
Date created: 25 July 2022
Link: https://discord.com/channels/376981415633354753/909753930353877052/1001045160714580009

Bug: Specified no 360 builds but the car still spun

Image: [https://www.reddit.com/r/RLCustomDesignsCSS/comments/w7jf7f/007s_aston_martin_valhalla_batmobile_1989_gravity/?](https://www.reddit.com/r/RLCustomDesignsCSS/comments/w7jf7f/007s_aston_martin_valhalla_batmobile_1989_gravity/?utm_medium=android_app&utm_source=share)

**Comment by vikasbhatia** [comment]
Tentatively resolved by adding forced map reset for every request. Pending testing.

This occurred as, previously:
* We were not resetting the map if the previous map was the same as the new map (to save time)
* There is no command to stop a turntable from spinning

Steps to reproduce:
1. Make a request on any given map with the "Rotate Car" option set to yes.
2. Make another request on the same map with the "Rotate Car" option set to no.

Since there was no logic which forced the turntable to stop, it just kept spinning as the new build was applied.

We have two options to fix this:
* Add a forced map reset between every build, even if the map is the same. This adds an additional 5-6 seconds for the map to settle. However it guarantees a reset of any turntable related actions.
* Refine the logic to not reset the map if it's the same as the previous one, but use `turntablemod_spin_table 1` to stop it spinning and use `turntablemod_degrees` to reset the position in which the car is facing.

All things considered, option 1 is much easier and nips other potential bugs in the bud, while option 2 might potentially save a few seconds of map-change time.

@Publicspac3 option 1 was already implemented before `turntablemod_degrees` was even a command, so we will decide with a couple of tests what's best.

**Comment by Publicspac3** [comment]
Fixed; Map is reset between requests.
